(SHOPPING '((COFFEE 100 GRAMMES) (BREAD 750 GRAMMES))) 
(COFFEE BREAD) 

(DEFUN SHOPPING (LIST) (LIST (FIRST (FIRST LIST)) (FIRST(FIRST(REST LIST))) ))

(INSERT-BEHIND '(FOOTBALL) '(I LIKE)) 
(I LIKE (FOOTBALL))

(DEFUN INSERT-BEHIND (A B) (REVERSE (CONS A (REVERSE B))))

(REMOVE-LAST '(I DO NOT LIKE BITING DOGS)) 
(I DO NOT LIKE BITING)

(DEFUN REMOVE-LAST (L) (REVERSE (REST (REVERSE L))) )

(REPLACE-LAST 'GREAT '(LIFE IS HARD)) 
(LIFE IS GREAT)

(DEFUN REPLACE-LAST (REPLACEMENT L) (REVERSE (CONS REPLACEMENT (REST (REVERSE L)))) )

(ADD-LENGTHS '(A B C D) '(E F)) 
6 

(DEFUN ADD-LENGTHS (L1 L2) (+ (LENGTH L1) (LENGTH L2)))

(ADD-LENGTH-TO-LIST '(X Y Z)) 
(X Y Z 3) 

(DEFUN 
  ADD-LENGTH-TO-LIST (L) 
  (REVERSE 
    (CONS (LENGTH L) (REVERSE L))) 
  )

(PALINDROME-P '(A B B A)) 
T 

(DEFUN PALINDROME-P (L) (EQUAL L (REVERSE L)))

(ONE-P '(ONE)) 

(DEFUN ONE-P (L)
  (= 1 (LENGTH L))
  )

(MORE-THAN-TWO-P '(A B)) 
NIL 

(DEFUN MORE-THAN-TWO-P (L)
  (< 2 (LENGTH L))
  )

(NREST 'A '(A B (X) D E)) 
4 

(DEFUN NREST (A L)
  (-
    (LENGTH
      (MEMBER A L)
    ) 1
  )
)

(NOT-NUMBERP 7) 
NIL 

(DEFUN NOT-NUMBERP (L) 
  (NOT (NUMBERP L))
  

(NUMBER-OR-LIST-P 'A) 
NIL

(DEFUN NUMBER-OR-LIST-P (X)
  (OR 
    (NUMBERP X)
    (LISTP X)
    )
  )

(DEFUN SAFE-LESSP (A B)
  (AND
    (NUMBERP A)
    (NUMBERP B)
    (< A B)
  )
)

(DEFUN WHAT-IS-IT (X)
  (COND
    ((NUMBERP X) 'NUMBER)
    ((LISTP X) 'LIST)
    ((SYMBOLP X) 'S-ATOM)
    (T 'DO-NOT-KNOW)
  )
)

(DEFUN COMPARE (X Y)
  (COND
    ((< X Y) 'ERSTE-KLEINER)
    ((> X Y) 'ERSTE-GROESSER)
    ((= X Y) 'BEIDE-GLEICH)))

(DEFUN INSERTS (ATOM LIST)
  (IF (MEMBER ATOM LIST)
    LIST
    (CONS ATOM LIST)))